name: rate_us_on_store
description: "Open application page on playstore & appstore"
version: 0.0.1
homepage: https://github.com/Dharini17/rate_us_on_store
documentation: https://pub.dev/documentation/rate_us_on_store

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0